export enum RouteParam {
  idPlayer = 'idPlayer',
  idUser = 'idUser',
  idCharacter = 'idCharacter',
  idCharacterCostume = 'idCharacterCostume',
  idGame = 'idGame',
  idMode = 'idMode',
  idMiniGame = 'idMiniGame',
  idPlatform = 'idPlatform',
  idStage = 'idStage',
  idScore = 'idScore',
  idScoreApprovalMotive = 'idScoreApprovalMotive',
  idSteamProfile = 'idSteamProfile',

  steamid = 'steamid',

  // OTHERS
  email = 'email',
  username = 'username',
  personaName = 'personaName',
  orderBy = 'orderBy',
  orderByDirection = 'orderByDirection',
  confirmationCode = 'confirmationCode',
  openidReturnTo = 'openid.return_to',
  uuid = 'uuid',
  action = 'action',
  limit = 'limit',
  page = 'page',
  itemsPerPage = 'itemsPerPage',
}
